spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    table: FLYWAY_SCHEMA_HISTORY
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none