CREATE TABLE KEYS
(
    ID   NUMBER(19) GENERATED ALWAYS AS IDENTITY,
    KEYS VARCHAR2(7) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    EXPIRED_AT  TIMESTAMP(6),
    CONSTRAINT UC_KEYS UNIQUE (KEYS),
);
