version: "3"
services:
  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379
    networks:
      - snap
  mongo:
    ports:
      - '27017:27017'
    container_name: dkrcomp-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
    networks:
      - snap
  mysql:
    image: mysql:8.0
    ports:
      - 5306:5306
    hostname: oracle
    networks:
      - snap

networks:
  snap:
    external: true